/* MFM Research Hub — sample data */

const PEOPLE = [
  { id: 'u1', name: 'Dr. Eran Ashwal', initials: 'EA', role: 'Principal Investigator', training: 'MFM Staff', email: 'eran.ashwal@example.ca', color: '#7A003C', joined: '2018-09', focus: 'Maternal-Fetal Medicine', hasPhoto: true, hasCV: true, bio: 'Clinician-scientist in Maternal-Fetal Medicine. Research interests include placental insufficiency, hypertensive disorders of pregnancy, fetal Doppler ultrasound, and prenatal diagnosis. Supervises medical students, residents and MFM fellows across a portfolio of clinical and translational projects.', pubmedAuthor: 'Ashwal E' },
  { id: 'u2', name: 'Dr. Aiden Park', initials: 'AP', role: 'Co-Investigator', training: 'MFM Staff', email: 'a.park@example.ca', color: '#0D5D78', joined: '2019-06', focus: 'Hypertensive disorders' },
  { id: 'u3', name: 'Dr. Rachel Voss', initials: 'RV', role: 'Co-Supervisor', training: 'MFM Staff', email: 'r.voss@example.ca', color: '#0E5B3D', joined: '2020-01', focus: 'Twin pregnancy outcomes' },
  { id: 'u4', name: 'Priya Shah', initials: 'PS', role: 'Resident', training: 'PGY-4 OB/GYN', email: 'p.shah@example.ca', color: '#B4760E', joined: '2024-07', focus: 'Cervical length screening', hasCV: true, bio: 'PGY-4 obstetrics and gynaecology resident with a research interest in preterm birth prediction.' },
  { id: 'u5', name: 'Jamal Okafor', initials: 'JO', role: 'Resident', training: 'PGY-3 OB/GYN', email: 'j.okafor@example.ca', color: '#9A2A2A', joined: '2024-07', focus: 'Doppler indices' },
  { id: 'u6', name: 'Sofia Marchetti', initials: 'SM', role: 'MFM Fellow', training: 'Fellow Year 2', email: 's.marchetti@example.ca', color: '#7A003C', joined: '2023-07', focus: 'AI obstetric ultrasound', hasCV: true, hasPhoto: true, bio: 'Second-year MFM fellow. Lead investigator on the AI-OBUS and CARDIO-PE studies; clinical interest in obstetric ultrasound innovation.' },
  { id: 'u7', name: 'David Tran', initials: 'DT', role: 'MFM Fellow', training: 'Fellow Year 1', email: 'd.tran@example.ca', color: '#5C002D', joined: '2025-07', focus: 'Hypertensive disorders' },
  { id: 'u8', name: 'Hannah Lindqvist', initials: 'HL', role: 'Medical Student', training: 'Clerkship', email: 'h.lindqvist@example.ca', color: '#137A4B', joined: '2025-09', focus: 'PPH risk' },
  { id: 'u9', name: 'Wei Chen', initials: 'WC', role: 'Medical Student', training: 'Research Year', email: 'w.chen@example.ca', color: '#0D5D78', joined: '2025-05', focus: 'Neonatal hypoglycemia' },
  { id: 'u10', name: 'Tomas Reyes', initials: 'TR', role: 'Medical Student', training: 'Clerkship', email: 't.reyes@example.ca', color: '#495965', joined: '2025-08', focus: 'MCA PSV protocol' },
  { id: 'u11', name: 'Aanya Krishnan', initials: 'AK', role: 'Research Coordinator', training: 'Coordinator', email: 'a.krishnan@example.ca', color: '#B4760E', joined: '2022-03', focus: 'REB / operations' },
  { id: 'u12', name: 'Marcus Whitfield', initials: 'MW', role: 'Research Coordinator', training: 'Coordinator', email: 'm.whitfield@example.ca', color: '#6B7785', joined: '2023-09', focus: 'Data access & agreements' },
  { id: 'u13', name: 'Dr. Elena Sokolov', initials: 'ES', role: 'Biostatistician', training: 'Collaborator', email: 'e.sokolov@example.ca', color: '#0E5B3D', joined: '2021-11', focus: 'Statistical analysis' },
  { id: 'u14', name: 'Dr. Owen Pritchard', initials: 'OP', role: 'Neonatology', training: 'Collaborator', email: 'o.pritchard@example.ca', color: '#0D5D78', joined: '2022-02', focus: 'Neonatal outcomes' },
  { id: 'u15', name: 'Lina Park', initials: 'LP', role: 'Volunteer', training: 'Data abstractor', email: 'l.park@example.ca', color: '#9C2E5E', joined: '2025-09', focus: 'Chart abstraction' },
];

const personById = (id) => PEOPLE.find(p => p.id === id);

const STATUSES = [
  'Idea / Concept', 'Protocol development', 'REB preparation', 'REB submitted', 'REB approved',
  'Data access pending', 'Data collection', 'Data cleaning', 'Statistical analysis',
  'Manuscript drafting', 'Internal review', 'Submitted to journal', 'Revision requested',
  'Accepted / Published', 'On hold', 'Completed', 'Archived'
];

const CONFERENCES = [
  { id: 'c1', name: 'SOGC Annual Clinical & Scientific Conference', short: 'SOGC 2026', dates: 'Jun 17–20, 2026', location: 'Vancouver, BC', abstractDue: '2026-02-28', earlyBird: '2026-04-15', url: 'https://sogc.org', tags: ['Canadian', 'General OB/GYN'], status: 'past_deadline' },
  { id: 'c2', name: 'SMFM Pregnancy Meeting', short: 'SMFM 2027', dates: 'Feb 1–6, 2027', location: 'Honolulu, HI', abstractDue: '2026-08-15', earlyBird: '2026-12-01', url: 'https://smfm.org', tags: ['MFM', 'High impact'], status: 'open' },
  { id: 'c3', name: 'ISUOG World Congress on Ultrasound in Obstetrics & Gynecology', short: 'ISUOG 2026', dates: 'Oct 11–15, 2026', location: 'Lisbon, Portugal', abstractDue: '2026-04-30', earlyBird: '2026-07-31', url: 'https://isuog.org', tags: ['Ultrasound', 'International'], status: 'past_deadline' },
  { id: 'c4', name: 'RCOG World Congress', short: 'RCOG 2026', dates: 'Jul 6–8, 2026', location: 'London, UK', abstractDue: '2026-03-01', earlyBird: '2026-05-01', url: 'https://rcog.org.uk', tags: ['International'], status: 'past_deadline' },
  { id: 'c5', name: 'DOHaD World Congress', short: 'DOHaD 2026', dates: 'Sep 23–26, 2026', location: 'Cape Town, South Africa', abstractDue: '2026-06-15', earlyBird: '2026-08-01', url: 'https://dohadsoc.org', tags: ['Developmental origins', 'Translational'], status: 'open' },
  { id: 'c6', name: 'Canadian Diabetes & Endocrinology Annual Meeting', short: 'CDEAM 2026', dates: 'Oct 28–31, 2026', location: 'Toronto, ON', abstractDue: '2026-06-30', earlyBird: '2026-08-15', url: '#', tags: ['Diabetes', 'Canadian'], status: 'open' },
  { id: 'c7', name: 'IFPA — Placenta Conference', short: 'IFPA 2026', dates: 'Aug 19–22, 2026', location: 'Sapporo, Japan', abstractDue: '2026-05-31', earlyBird: '2026-07-15', url: '#', tags: ['Placenta', 'International'], status: 'closing_soon' },
  { id: 'c8', name: 'CAOG Annual Conference', short: 'CAOG 2026', dates: 'Nov 12–14, 2026', location: 'Montreal, QC', abstractDue: '2026-07-31', earlyBird: '2026-09-15', url: '#', tags: ['Canadian'], status: 'open' },
];

// Project intent to submit to conferences
const ABSTRACT_INTENTS = [
  { project: 'p3', conference: 'c2', status: 'planned', notes: 'Late-breaker if SOGC slot opens' },
  { project: 'p3', conference: 'c6', owner: 'u6', status: 'planned', notes: 'Primary submission target — Marchetti to draft' },
  { project: 'p1', conference: 'c2', owner: 'u4', status: 'planned', notes: 'Submit poster' },
  { project: 'p12', conference: 'c1', status: 'submitted', notes: 'Submitted Feb 22; accepted as oral' },
  { project: 'p4', conference: 'c3', status: 'planned', notes: 'Aim for video session' },
  { project: 'p8', conference: 'c7', status: 'considering', notes: 'Pending biomarker data readiness' },
];


const BINS = [
  { id: 'Preterm Labour', label: 'Preterm Labour', desc: 'Spontaneous preterm birth prediction, prevention and management; cervical length screening; tocolysis; antenatal corticosteroids.', cover: 'maroon', icon: 'clock' },
  { id: 'Placenta-Mediated', label: 'Placenta-Mediated Complications', desc: 'Hypertensive disorders, fetal growth restriction, placental insufficiency biomarkers and maternal cardiovascular consequences.', cover: 'gold', icon: 'target' },
  { id: 'Diabetes', label: 'Diabetes in Pregnancy', desc: 'Gestational and pre-existing diabetes, glycemic control, fetal growth, neonatal outcomes and screening thresholds.', cover: 'bay', icon: 'activity' },
  { id: 'Ultrasound', label: 'Ultrasound & Imaging', desc: 'Obstetric ultrasound workflow, Doppler standardization, AI-assisted measurement and imaging quality protocols.', cover: 'bay', icon: 'eye' },
  { id: 'Prenatal Diagnosis', label: 'Prenatal Diagnosis', desc: 'Screening, fetal anomaly evaluation, twin pregnancy registry and diagnostic strategy.', cover: 'forest', icon: 'target' },
  { id: 'Labour & Delivery', label: 'Labour & Delivery', desc: 'Intrapartum care, postpartum hemorrhage risk, neonatal hypoglycemia and outcome stratification at term.', cover: 'grey', icon: 'stethoscope' },
];


const today = new Date('2026-05-24');
const daysFrom = (n) => {
  const d = new Date(today); d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
};

const PROJECTS = [
  {
    id: 'p1', bin: 'Preterm Labour',
    title: 'Prediction Capacity of Cervical Length Measurement in Early Pregnancy',
    acronym: 'CERVI-PRED',
    description: 'Retrospective cohort evaluating whether mid-trimester cervical length predicts spontaneous preterm birth in a low-risk obstetric population.',
    category: 'Clinical research',
    studyDesign: 'Retrospective cohort',
    status: 'Statistical analysis',
    health: 'green',
    priority: 'High',
    progress: 68,
    pi: 'u1',
    lead: 'u4',
    members: ['u4', 'u1', 'u13', 'u11'],
    reb: 'Approved', rebExpiry: '2026-08-11',
    dataSource: 'BORN Ontario + local OB EHR',
    targetJournal: 'AJOG MFM',
    start: '2025-02-10',
    target: '2026-09-30',
    lastUpdate: daysFrom(-3),
    nextMilestone: 'Multivariable model finalized',
    nextDue: daysFrom(11),
    fileCount: 24,
    awaitingUpdate: false,
    awaitingReview: false,
    coverColor: 'maroon',
  },
  {
    id: 'p2', bin: 'Preterm Labour',
    title: 'Doppler Indices Before and After Antenatal Corticosteroids (Celestone)',
    acronym: 'DOPPLER-CEL',
    description: 'Prospective observational study quantifying short-term changes in umbilical and middle cerebral artery Doppler indices following a course of betamethasone.',
    category: 'Clinical research',
    studyDesign: 'Prospective observational',
    status: 'Data collection',
    health: 'amber',
    priority: 'High',
    progress: 42,
    pi: 'u1',
    lead: 'u5',
    members: ['u5', 'u1', 'u11'],
    reb: 'Approved', rebExpiry: '2026-07-04',
    dataSource: 'Antenatal Clinic + L&D',
    targetJournal: 'Ultrasound Obstet Gynecol',
    start: '2025-05-01',
    target: '2026-12-15',
    lastUpdate: daysFrom(-12),
    nextMilestone: 'Reach 60-patient recruitment milestone',
    nextDue: daysFrom(-4),
    fileCount: 18,
    awaitingUpdate: true,
    awaitingReview: false,
    coverColor: 'gold',
  },
  {
    id: 'p3', bin: 'Diabetes',
    title: 'Fetal Growth Restriction and Gestational Diabetes Outcomes',
    acronym: 'FGR-GDM',
    description: 'Multi-year cohort study examining neonatal outcomes in pregnancies with concurrent FGR and gestational diabetes, stratified by glycemic control.',
    category: 'Clinical research',
    studyDesign: 'Retrospective cohort',
    status: 'Manuscript drafting',
    health: 'green',
    priority: 'High',
    progress: 82,
    pi: 'u1',
    lead: 'u6',
    members: ['u6', 'u1', 'u14', 'u13'],
    reb: 'Approved', rebExpiry: '2026-09-15',
    dataSource: 'Hospital perinatal database',
    targetJournal: 'Diabetes Care',
    start: '2024-09-12',
    target: '2026-07-30',
    lastUpdate: daysFrom(-1),
    nextMilestone: 'PI review of full manuscript',
    nextDue: daysFrom(6),
    fileCount: 41,
    awaitingUpdate: false,
    awaitingReview: true,
    coverColor: 'forest',
  },
  {
    id: 'p4', bin: 'Ultrasound',
    title: 'AI-Enabled Obstetric Ultrasound Workflow Study',
    acronym: 'AI-OBUS',
    description: 'Prospective evaluation of an AI-assisted measurement tool versus standard sonographer workflow across third-trimester growth scans.',
    category: 'Translational / AI',
    studyDesign: 'Prospective comparative',
    status: 'REB approved',
    health: 'green',
    priority: 'High',
    progress: 30,
    pi: 'u1',
    lead: 'u6',
    members: ['u6', 'u1', 'u11', 'u12'],
    reb: 'Approved', rebExpiry: '2026-11-04',
    dataSource: 'Ultrasound unit (AI tool + standard)',
    targetJournal: 'NPJ Digital Medicine',
    start: '2025-11-04',
    target: '2027-03-31',
    lastUpdate: daysFrom(-6),
    nextMilestone: 'First 25 scans completed',
    nextDue: daysFrom(20),
    fileCount: 12,
    awaitingUpdate: false,
    awaitingReview: false,
    coverColor: 'bay',
  },
  {
    id: 'p5', bin: 'Labour & Delivery',
    title: 'Neonatal Hypoglycemia and Perinatal Risk Factors',
    acronym: 'NEO-HYPO',
    description: 'Case-control study identifying antepartum and intrapartum predictors of clinically significant neonatal hypoglycemia in late-preterm and term infants.',
    category: 'Clinical research',
    studyDesign: 'Case-control',
    status: 'Data cleaning',
    health: 'amber',
    priority: 'Medium',
    progress: 55,
    pi: 'u1',
    lead: 'u9',
    members: ['u9', 'u1', 'u14', 'u15'],
    reb: 'Approved', rebExpiry: '2026-06-20',
    dataSource: 'NICU + birth registry',
    targetJournal: 'J Pediatr',
    start: '2024-11-20',
    target: '2026-10-30',
    lastUpdate: daysFrom(-18),
    nextMilestone: 'Cleaned dataset ready for analysis',
    nextDue: daysFrom(2),
    fileCount: 22,
    awaitingUpdate: true,
    awaitingReview: false,
    coverColor: 'maroon',
  },
  {
    id: 'p6', bin: 'Ultrasound',
    title: 'MCA Peak Systolic Velocity Standardization Protocol',
    acronym: 'MCA-STD',
    description: 'Development and pilot validation of an institutional standardization protocol for middle cerebral artery PSV measurement in fetal anemia surveillance.',
    category: 'Quality improvement',
    studyDesign: 'Protocol / QI pilot',
    status: 'Protocol development',
    health: 'green',
    priority: 'Medium',
    progress: 18,
    pi: 'u1',
    lead: 'u10',
    members: ['u10', 'u1', 'u11'],
    reb: 'Not required', rebExpiry: null,
    dataSource: 'Ultrasound unit (QI dataset)',
    targetJournal: 'J Obstet Gynaecol Can',
    start: '2026-02-15',
    target: '2027-02-28',
    lastUpdate: daysFrom(-2),
    nextMilestone: 'Protocol v2 drafted',
    nextDue: daysFrom(9),
    fileCount: 7,
    awaitingUpdate: false,
    awaitingReview: false,
    coverColor: 'bay',
  },
  {
    id: 'p7', bin: 'Placenta-Mediated',
    title: 'Hypertensive Disorders in Pregnancy: Outcomes Protocol',
    acronym: 'HDP-OUT',
    description: 'Multi-centre prospective cohort tracking maternal and neonatal outcomes across the spectrum of hypertensive disorders in pregnancy, with emphasis on long-term cardiovascular sequelae.',
    category: 'Clinical research',
    studyDesign: 'Prospective multi-centre cohort',
    status: 'REB submitted',
    health: 'amber',
    priority: 'High',
    progress: 22,
    pi: 'u1',
    lead: 'u7',
    members: ['u7', 'u1', 'u2', 'u11', 'u12'],
    reb: 'Under review', rebExpiry: null,
    dataSource: 'Multi-centre EHR + outcomes registry',
    targetJournal: 'BJOG',
    start: '2025-08-01',
    target: '2028-06-30',
    lastUpdate: daysFrom(-9),
    nextMilestone: 'REB response & revisions',
    nextDue: daysFrom(-1),
    fileCount: 31,
    awaitingUpdate: false,
    awaitingReview: true,
    coverColor: 'maroon',
  },
  {
    id: 'p8', bin: 'Placenta-Mediated',
    title: 'Placental Insufficiency Biomarker Panel',
    acronym: 'PLAC-BIO',
    description: 'Pilot validation of a multiplex biomarker panel (sFlt-1, PlGF, GDF-15) for early identification of placental insufficiency in high-risk pregnancies.',
    category: 'Translational',
    studyDesign: 'Pilot validation',
    status: 'Data access pending',
    health: 'amber',
    priority: 'High',
    progress: 15,
    pi: 'u1',
    lead: 'u7',
    members: ['u7', 'u1', 'u12', 'u13'],
    reb: 'Approved', rebExpiry: '2026-06-05',
    dataSource: 'Bio-bank + research lab',
    targetJournal: 'Placenta',
    start: '2026-01-10',
    target: '2027-09-30',
    lastUpdate: daysFrom(-21),
    nextMilestone: 'Data access agreement signed',
    nextDue: daysFrom(-7),
    fileCount: 9,
    awaitingUpdate: true,
    awaitingReview: false,
    coverColor: 'forest',
  },
  {
    id: 'p9', bin: 'Prenatal Diagnosis',
    title: 'Twin Pregnancy Outcomes Registry',
    acronym: 'TWIN-REG',
    description: 'Establishment of a prospective registry of twin pregnancies to characterize outcomes by chorionicity, gestational age at delivery, and intertwin discordance.',
    category: 'Registry',
    studyDesign: 'Prospective registry',
    status: 'Data collection',
    health: 'green',
    priority: 'Medium',
    progress: 50,
    pi: 'u1',
    lead: 'u4',
    members: ['u4', 'u1', 'u3', 'u11'],
    reb: 'Approved', rebExpiry: '2027-04-01',
    dataSource: 'MFM clinic + registry',
    targetJournal: 'AJOG',
    start: '2024-04-01',
    target: '2027-04-01',
    lastUpdate: daysFrom(-5),
    nextMilestone: '200-pregnancy enrollment',
    nextDue: daysFrom(14),
    fileCount: 28,
    awaitingUpdate: false,
    awaitingReview: false,
    coverColor: 'bay',
  },
  {
    id: 'p10', bin: 'Placenta-Mediated',
    title: 'Maternal Cardiac Function in Preeclampsia',
    acronym: 'CARDIO-PE',
    description: 'Cross-sectional echocardiographic study of maternal cardiac function in preeclampsia compared to normotensive matched controls.',
    category: 'Clinical research',
    studyDesign: 'Cross-sectional',
    status: 'Submitted to journal',
    health: 'green',
    priority: 'Medium',
    progress: 92,
    pi: 'u1',
    lead: 'u6',
    members: ['u6', 'u1', 'u2', 'u13'],
    reb: 'Approved', rebExpiry: '2026-10-15',
    dataSource: 'Cardiology + OB',
    targetJournal: 'Hypertension',
    start: '2023-10-01',
    target: '2026-06-15',
    lastUpdate: daysFrom(-2),
    nextMilestone: 'Reviewer comments expected',
    nextDue: daysFrom(7),
    fileCount: 36,
    awaitingUpdate: false,
    awaitingReview: false,
    coverColor: 'maroon',
  },
  {
    id: 'p11', bin: 'Labour & Delivery',
    title: 'Postpartum Hemorrhage Risk Stratification',
    acronym: 'PPH-STRAT',
    description: 'Development and internal validation of a postpartum hemorrhage risk prediction model integrating antenatal, intrapartum and patient-reported factors.',
    category: 'Clinical research',
    studyDesign: 'Prediction model development',
    status: 'Idea / Concept',
    health: 'grey',
    priority: 'Low',
    progress: 5,
    pi: 'u1',
    lead: 'u8',
    members: ['u8', 'u1', 'u13'],
    reb: 'Not yet submitted', rebExpiry: null,
    dataSource: 'L&D + outcomes registry (planned)',
    targetJournal: 'TBD',
    start: '2026-04-15',
    target: '2027-12-31',
    lastUpdate: daysFrom(-15),
    nextMilestone: 'Literature review complete',
    nextDue: daysFrom(22),
    fileCount: 3,
    awaitingUpdate: false,
    awaitingReview: false,
    coverColor: 'grey',
  },
  {
    id: 'p12', bin: 'Preterm Labour',
    title: 'Antenatal Corticosteroid Timing Review',
    acronym: 'ACS-TIMING',
    description: 'Systematic review and meta-analysis of optimal timing of antenatal corticosteroid administration relative to delivery for late preterm infants.',
    category: 'Evidence synthesis',
    studyDesign: 'Systematic review',
    status: 'Internal review',
    health: 'green',
    priority: 'Medium',
    progress: 76,
    pi: 'u1',
    lead: 'u5',
    members: ['u5', 'u1', 'u14'],
    reb: 'Not required', rebExpiry: null,
    dataSource: 'Published literature',
    targetJournal: 'Cochrane',
    start: '2024-12-01',
    target: '2026-08-30',
    lastUpdate: daysFrom(-4),
    nextMilestone: 'Internal review comments returned',
    nextDue: daysFrom(3),
    fileCount: 19,
    awaitingUpdate: false,
    awaitingReview: true,
    coverColor: 'gold',
  },
];

const MILESTONES = {
  p1: [
    { id: 'm1', title: 'Project idea finalized', owner: 'u1', due: '2025-02-15', status: 'done', completed: '2025-02-14' },
    { id: 'm2', title: 'Literature review completed', owner: 'u4', due: '2025-04-01', status: 'done', completed: '2025-04-08' },
    { id: 'm3', title: 'Protocol drafted', owner: 'u4', due: '2025-05-01', status: 'done', completed: '2025-04-28' },
    { id: 'm4', title: 'REB submission', owner: 'u11', due: '2025-06-01', status: 'done', completed: '2025-06-03' },
    { id: 'm5', title: 'REB approval', owner: 'u11', due: '2025-08-15', status: 'done', completed: '2025-08-11' },
    { id: 'm6', title: 'Data extraction complete', owner: 'u4', due: '2025-12-15', status: 'done', completed: '2025-12-22' },
    { id: 'm7', title: 'Data cleaning complete', owner: 'u4', due: '2026-02-28', status: 'done', completed: '2026-03-05' },
    { id: 'm8', title: 'Multivariable model finalized', owner: 'u13', due: daysFrom(11), status: 'in_progress', completed: null },
    { id: 'm9', title: 'Manuscript first draft', owner: 'u4', due: daysFrom(60), status: 'todo', completed: null },
    { id: 'm10', title: 'Journal submission', owner: 'u1', due: daysFrom(120), status: 'todo', completed: null },
  ],
  p2: [
    { id: 'm1', title: 'Protocol finalized', owner: 'u5', due: '2025-04-15', status: 'done', completed: '2025-04-20' },
    { id: 'm2', title: 'REB approval', owner: 'u11', due: '2025-06-30', status: 'done', completed: '2025-07-04' },
    { id: 'm3', title: 'Recruitment opens', owner: 'u11', due: '2025-08-01', status: 'done', completed: '2025-08-05' },
    { id: 'm4', title: 'Reach 60-patient recruitment', owner: 'u5', due: daysFrom(-4), status: 'overdue', completed: null },
    { id: 'm5', title: 'Interim analysis', owner: 'u13', due: daysFrom(40), status: 'todo', completed: null },
    { id: 'm6', title: 'Recruitment complete (n=120)', owner: 'u5', due: daysFrom(200), status: 'todo', completed: null },
  ],
};

const TASKS = {
  p1: [
    { id: 't1', title: 'Re-run multivariable logistic regression with updated covariates', owner: 'u13', priority: 'High', status: 'in_progress', due: daysFrom(4) },
    { id: 't2', title: 'Update Table 1 with restricted cohort', owner: 'u4', priority: 'High', status: 'in_progress', due: daysFrom(6) },
    { id: 't3', title: 'Draft Methods section', owner: 'u4', priority: 'Medium', status: 'todo', due: daysFrom(14) },
    { id: 't4', title: 'Send variable dictionary to biostatistician', owner: 'u4', priority: 'High', status: 'done', due: daysFrom(-8) },
    { id: 't5', title: 'Confirm BORN data access renewal', owner: 'u11', priority: 'Medium', status: 'waiting', due: daysFrom(10) },
    { id: 't6', title: 'PI to review preliminary model coefficients', owner: 'u1', priority: 'High', status: 'review', due: daysFrom(3) },
    { id: 't7', title: 'Add sensitivity analysis (n=2 vs n≥3 measurements)', owner: 'u13', priority: 'Medium', status: 'todo', due: daysFrom(18) },
    { id: 't8', title: 'Reach out to neonatology co-author', owner: 'u4', priority: 'Low', status: 'todo', due: daysFrom(8) },
  ],
  p2: [
    { id: 't1', title: 'Recruit at clinic on Tuesday and Thursday', owner: 'u5', priority: 'High', status: 'in_progress', due: daysFrom(2) },
    { id: 't2', title: 'Follow-up Doppler at 24h post-second dose', owner: 'u5', priority: 'High', status: 'in_progress', due: daysFrom(1) },
    { id: 't3', title: 'Update REDCap form with new MCA fields', owner: 'u11', priority: 'Medium', status: 'todo', due: daysFrom(5) },
    { id: 't4', title: 'PI to review recruitment dashboard', owner: 'u1', priority: 'High', status: 'review', due: daysFrom(1) },
    { id: 't5', title: 'Submit annual REB renewal', owner: 'u11', priority: 'High', status: 'waiting', due: daysFrom(30) },
  ],
};

const UPDATES = [
  { id: 'up1', project: 'p1', user: 'u4', date: daysFrom(-3), percent: 68,
    completed: 'Finalized variable selection and re-ran multivariable logistic regression with corrected reference group. Pulled updated descriptive stats for Table 1.',
    inProgress: 'Drafting Methods section and updating model diagnostics figure.',
    barriers: 'Three of 412 records have ambiguous gestational age at measurement — flagged for chart review.',
    helpNeeded: 'Could the PI confirm the cut-point for "very low risk" vs "low risk" categorization?',
    next: 'Complete Methods + draft Results next week. Send to biostats for review by next Monday.',
    piStatus: 'commented' },
  { id: 'up2', project: 'p3', user: 'u6', date: daysFrom(-1), percent: 82,
    completed: 'Manuscript full draft complete. Figures finalized at 300dpi. Co-author Dr. Pritchard returned neonatology section.',
    inProgress: 'Incorporating Dr. Sokolov\'s statistical edits.',
    barriers: 'None.',
    helpNeeded: 'Ready for PI full review.',
    next: 'Submit to PI by Friday. Aim for Diabetes Care submission within 3 weeks.',
    piStatus: 'pending' },
  { id: 'up3', project: 'p5', user: 'u9', date: daysFrom(-18), percent: 55,
    completed: 'Cleaned 60% of NICU dataset. Resolved 28 duplicate records.',
    inProgress: 'Cleaning remaining 40%, focus on birth weight outliers.',
    barriers: 'EHR export missing maternal BMI for 14 cases — coordinator following up.',
    helpNeeded: 'Decision on how to handle BMI missingness for analysis.',
    next: 'Complete cleaning, then descriptive stats.',
    piStatus: 'requested_clarification' },
  { id: 'up4', project: 'p12', user: 'u5', date: daysFrom(-4), percent: 76,
    completed: 'Full systematic review draft prepared. Forest plots for primary and secondary outcomes complete.',
    inProgress: 'Awaiting internal review comments from co-authors.',
    barriers: 'None.',
    helpNeeded: 'None at this stage.',
    next: 'Address review comments and prepare for journal submission.',
    piStatus: 'approved' },
];

const ACTIVITY = [
  { id: 'a1', project: 'p3', user: 'u6', type: 'update', text: 'submitted a progress update', detail: 'Manuscript draft complete', date: daysFrom(-1) },
  { id: 'a2', project: 'p1', user: 'u13', type: 'file', text: 'uploaded a file', detail: 'multivariable-model-v3.R', date: daysFrom(-2) },
  { id: 'a3', project: 'p10', user: 'u1', type: 'status', text: 'changed status', detail: 'Internal review → Submitted to journal', date: daysFrom(-2) },
  { id: 'a4', project: 'p2', user: 'u5', type: 'milestone', text: 'flagged a milestone overdue', detail: 'Reach 60-patient recruitment', date: daysFrom(-4) },
  { id: 'a5', project: 'p12', user: 'u14', type: 'comment', text: 'commented on a draft', detail: '"Consider adding sensitivity analysis for late-preterm subset"', date: daysFrom(-4) },
  { id: 'a6', project: 'p4', user: 'u11', type: 'file', text: 'uploaded a file', detail: 'AI-OBUS-REB-approval-letter.pdf', date: daysFrom(-6) },
  { id: 'a7', project: 'p7', user: 'u7', type: 'update', text: 'submitted a progress update', detail: 'REB response received', date: daysFrom(-9) },
  { id: 'a8', project: 'p8', user: 'u12', type: 'comment', text: 'flagged a blocker', detail: 'Data access agreement still pending lab signoff', date: daysFrom(-7) },
  { id: 'a9', project: 'p5', user: 'u1', type: 'comment', text: 'requested clarification', detail: 'on NEO-HYPO progress update', date: daysFrom(-17) },
  { id: 'a10', project: 'p9', user: 'u4', type: 'file', text: 'uploaded files', detail: '4 enrollment forms (May batch)', date: daysFrom(-5) },
];

const NOTIFICATIONS = [
  { id: 'n1', type: 'overdue', project: 'p2', text: 'Recruitment milestone overdue (4 days)', date: daysFrom(-4), unread: true },
  { id: 'n2', type: 'review', project: 'p3', text: 'Sofia submitted manuscript for PI review', date: daysFrom(-1), unread: true },
  { id: 'n3', type: 'update', project: 'p1', text: 'Priya submitted a progress update', date: daysFrom(-3), unread: true },
  { id: 'n4', type: 'overdue', project: 'p7', text: 'REB response milestone due yesterday', date: daysFrom(-1), unread: true },
  { id: 'n5', type: 'overdue', project: 'p8', text: 'Data access agreement overdue', date: daysFrom(-7), unread: false },
  { id: 'n6', type: 'deadline', project: 'p5', text: 'Cleaned dataset due in 2 days', date: daysFrom(2), unread: false },
  { id: 'n7', type: 'file', project: 'p4', text: 'REB approval letter uploaded', date: daysFrom(-6), unread: false },
];

const PUBLICATIONS = [
  { id: 'pub1', pmid: '40123456', year: 2026, month: 'Mar', title: 'Mid-trimester cervical length and risk of spontaneous preterm birth in low-risk pregnancies: a multi-centre cohort analysis', authors: 'Ashwal E, Shah P, Sokolov E, Park A, et al.', journal: 'BJOG', volume: '133(4)', pages: '442–453', doi: '10.1111/1471-0528.17852', type: 'Original article', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub2', pmid: '39654321', year: 2025, month: 'Nov', title: 'Maternal cardiac remodelling in preeclampsia: a systematic echocardiographic review', authors: 'Marchetti S, Ashwal E, Park A.', journal: 'Hypertension in Pregnancy', volume: '44(3)', pages: '155–168', doi: '10.1080/10641955.2025.2298142', type: 'Review', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub3', pmid: '39512876', year: 2025, month: 'Aug', title: 'Doppler indices following antenatal corticosteroids in late preterm pregnancy: a prospective observational pilot', authors: 'Ashwal E, Okafor J, Marchetti S.', journal: 'Ultrasound Obstet Gynecol', volume: '66(2)', pages: '189–197', doi: '10.1002/uog.27812', type: 'Original article', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub4', pmid: '39301142', year: 2025, month: 'May', title: 'Antenatal corticosteroids in late preterm pregnancy: a network meta-analysis of timing strategies', authors: 'Okafor J, Pritchard O, Ashwal E.', journal: 'Cochrane Database Syst Rev', volume: '2025(5)', pages: 'CD014731', doi: '10.1002/14651858.CD014731', type: 'Systematic review', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub5', pmid: '38997254', year: 2024, month: 'Dec', title: 'Twin pregnancy registry: design, governance and baseline characteristics', authors: 'Shah P, Voss R, Ashwal E.', journal: 'J Obstet Gynaecol Can', volume: '46(12)', pages: '102589', doi: '10.1016/j.jogc.2024.102589', type: 'Methods', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub6', pmid: '38812011', year: 2024, month: 'Jul', title: 'Maternal BMI and short-term Doppler variability after betamethasone: a sub-analysis', authors: 'Ashwal E, Marchetti S.', journal: 'Acta Obstet Gynecol Scand', volume: '103(7)', pages: '1322–1330', doi: '10.1111/aogs.14821', type: 'Original article', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub7', pmid: '38456712', year: 2024, month: 'Mar', title: 'Hypertensive disorders of pregnancy and long-term maternal cardiovascular outcomes: a Canadian cohort', authors: 'Park A, Tran D, Ashwal E.', journal: 'Pregnancy Hypertens', volume: '35', pages: '88–95', doi: '10.1016/j.preghy.2024.02.008', type: 'Original article', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub8', pmid: 'in-press', year: 2026, month: 'In press', title: 'Neonatal hypoglycemia in late-preterm infants: a case-control analysis of perinatal predictors', authors: 'Chen W, Pritchard O, Ashwal E.', journal: 'Journal of Pediatrics', volume: 'In press', pages: '—', doi: 'pending', type: 'Original article', status: 'Accepted', source: 'manual', addedBy: 'u1' },
  { id: 'pub9', pmid: '37992145', year: 2023, month: 'Sep', title: 'Cervical length screening: implementation in a busy MFM clinic — lessons learned', authors: 'Ashwal E, Krishnan A.', journal: 'J Matern Fetal Neonatal Med', volume: '36(9)', pages: '2241712', doi: '10.1080/14767058.2023.2241712', type: 'Commentary', status: 'Published', source: 'pubmed', addedBy: 'auto' },
];

const GRANTS = [
  { id: 'g1', title: 'Cervical length screening and prediction of spontaneous preterm birth', funder: 'CIHR — Canadian Institutes of Health Research', mechanism: 'Project Grant', role: 'Principal Investigator', amount: 385000, currency: 'CAD', start: '2024-04', end: '2027-03', status: 'active', projects: ['p1'] },
  { id: 'g2', title: 'AI-enabled obstetric ultrasound: feasibility and validation', funder: 'SOGC Foundation', mechanism: 'Research Grant', role: 'Principal Investigator', amount: 75000, currency: 'CAD', start: '2025-09', end: '2026-12', status: 'active', projects: ['p4'] },
  { id: 'g3', title: 'Placental insufficiency biomarker discovery — pilot', funder: 'McMaster Department of OB/GYN', mechanism: 'Internal Research Fund', role: 'Principal Investigator', amount: 25000, currency: 'CAD', start: '2026-01', end: '2027-06', status: 'active', projects: ['p8'] },
  { id: 'g4', title: 'Twin pregnancy registry and longitudinal outcomes', funder: 'PSI Foundation', mechanism: 'Operating Grant', role: 'Co-Investigator', amount: 120000, currency: 'CAD', start: '2024-09', end: '2027-08', status: 'active', projects: ['p9'] },
  { id: 'g5', title: 'Doppler standardization for fetal anemia surveillance', funder: 'Hamilton Health Sciences Foundation', mechanism: 'Innovation Grant', role: 'Principal Investigator', amount: 18000, currency: 'CAD', start: '2023-09', end: '2025-08', status: 'completed', projects: ['p6'] },
];

const AWARDS = [
  { id: 'aw1', year: 2025, title: 'Junior Investigator Award', org: 'Society for Maternal-Fetal Medicine (SMFM)', recipient: 'u1', desc: 'Recognizing early-career contributions to maternal-fetal medicine research.', tier: 'national' },
  { id: 'aw2', year: 2025, title: 'Best Original Abstract — Obstetrics', org: 'SOGC Annual Conference', recipient: 'u6', desc: 'For "Maternal cardiac remodelling in preeclampsia: longitudinal echocardiographic findings."', tier: 'national' },
  { id: 'aw3', year: 2024, title: 'Trainee Research Award', org: 'Canadian Society of Perinatologists', recipient: 'u4', desc: 'For excellence in resident-led research on cervical length screening.', tier: 'national' },
  { id: 'aw4', year: 2024, title: 'Department Teaching Excellence Award', org: 'McMaster Faculty of Health Sciences', recipient: 'u1', desc: 'Recognizing outstanding mentorship of medical trainees in clinical research.', tier: 'institutional' },
  { id: 'aw5', year: 2024, title: 'Best Resident Presentation', org: 'RCOG World Congress', recipient: 'u5', desc: 'For meta-analysis of antenatal corticosteroid timing in late preterm pregnancy.', tier: 'international' },
  { id: 'aw6', year: 2023, title: 'Letko Outstanding Research Trainee Award', org: 'Hamilton Health Sciences', recipient: 'u6', desc: 'For sustained excellence as a fellow in MFM research.', tier: 'institutional' },
];

const PRESENTATIONS = [
  { id: 'pr1', year: 2026, month: 'Feb', title: 'AI-enabled obstetric ultrasound: preliminary validation in third-trimester growth scans', conference: 'SMFM Pregnancy Meeting 2026', location: 'Dallas, TX', presenter: 'u6', type: 'oral', authors: 'Marchetti S, Ashwal E, Krishnan A.', linkedProject: 'p4' },
  { id: 'pr2', year: 2025, month: 'Jun', title: 'Cervical length screening and spontaneous preterm birth in a low-risk cohort', conference: 'SOGC Annual Conference 2025', location: 'Halifax, NS', presenter: 'u4', type: 'oral', authors: 'Shah P, Ashwal E, Sokolov E.', linkedProject: 'p1' },
  { id: 'pr3', year: 2025, month: 'Oct', title: 'Doppler indices following antenatal corticosteroids: a prospective observational study', conference: 'ISUOG World Congress 2025', location: 'Athens, Greece', presenter: 'u5', type: 'oral', authors: 'Okafor J, Ashwal E, Marchetti S.', linkedProject: 'p2' },
  { id: 'pr4', year: 2025, month: 'Oct', title: 'MCA-PSV standardization in fetal anemia surveillance: pilot results', conference: 'ISUOG World Congress 2025', location: 'Athens, Greece', presenter: 'u10', type: 'poster', authors: 'Reyes T, Ashwal E.', linkedProject: 'p6' },
  { id: 'pr5', year: 2025, month: 'May', title: 'Maternal cardiac remodelling in preeclampsia: longitudinal echocardiographic findings', conference: 'SOGC Annual Conference 2025', location: 'Halifax, NS', presenter: 'u6', type: 'oral', authors: 'Marchetti S, Park A, Ashwal E.', linkedProject: 'p10' },
  { id: 'pr6', year: 2024, month: 'Nov', title: 'Antenatal corticosteroid timing in late preterm pregnancy: a network meta-analysis', conference: 'CAOG Annual Conference 2024', location: 'Vancouver, BC', presenter: 'u5', type: 'invited', authors: 'Okafor J, Ashwal E.', linkedProject: 'p12' },
  { id: 'pr7', year: 2024, month: 'Jul', title: 'Twin pregnancy registry: design and baseline characteristics', conference: 'RCOG World Congress 2024', location: 'London, UK', presenter: 'u4', type: 'poster', authors: 'Shah P, Voss R, Ashwal E.', linkedProject: 'p9' },
  { id: 'pr8', year: 2024, month: 'Feb', title: 'Hypertensive disorders of pregnancy and long-term maternal cardiovascular outcomes', conference: 'SMFM Pregnancy Meeting 2024', location: 'National Harbor, MD', presenter: 'u7', type: 'oral', authors: 'Tran D, Park A, Ashwal E.', linkedProject: 'p7' },
  { id: 'pr9', year: 2024, month: 'Sep', title: 'Neonatal hypoglycemia in late-preterm infants: preliminary case-control results', conference: 'Canadian Pediatric Society 2024', location: 'Toronto, ON', presenter: 'u9', type: 'poster', authors: 'Chen W, Pritchard O, Ashwal E.', linkedProject: 'p5' },
  { id: 'pr10', year: 2023, month: 'May', title: 'Cervical length screening implementation: a quality improvement perspective', conference: 'SOGC Annual Conference 2023', location: 'Montreal, QC', presenter: 'u1', type: 'invited', authors: 'Ashwal E, Krishnan A.', linkedProject: 'p1' },
];

// chip colour helpers
const statusChipClass = (status) => {
  const s = status.toLowerCase();
  if (s.includes('idea') || s.includes('protocol dev') || s.includes('hold') || s.includes('archived')) return 'chip-grey';
  if (s.includes('reb prep') || s.includes('reb submitted') || s.includes('data access')) return 'chip-amber';
  if (s.includes('reb approved') || s.includes('data collection') || s.includes('data cleaning')) return 'chip-bayfront';
  if (s.includes('statistical') || s.includes('manuscript') || s.includes('internal review')) return 'chip-maroon';
  if (s.includes('submitted to journal') || s.includes('revision')) return 'chip-gold';
  if (s.includes('accepted') || s.includes('completed')) return 'chip-green';
  return 'chip-grey';
};

const healthLabel = (h) => ({ green: 'On track', amber: 'Needs attention', red: 'Delayed', grey: 'Inactive' }[h] || h);
const priorityChip = (p) => ({ High: 'chip-red', Medium: 'chip-amber', Low: 'chip-grey' }[p] || 'chip-grey');

const fmtDate = (iso) => {
  if (!iso) return '—';
  const d = new Date(iso);
  return d.toLocaleDateString('en-CA', { month: 'short', day: 'numeric', year: 'numeric' });
};
const relDate = (iso) => {
  if (!iso) return '—';
  const d = new Date(iso);
  const diff = Math.round((d - today) / (24 * 3600 * 1000));
  if (diff === 0) return 'Today';
  if (diff === 1) return 'Tomorrow';
  if (diff === -1) return 'Yesterday';
  if (diff > 0 && diff < 14) return `in ${diff}d`;
  if (diff < 0 && diff > -14) return `${-diff}d ago`;
  return fmtDate(iso);
};

Object.assign(window, {
  PEOPLE, PROJECTS, MILESTONES, TASKS, UPDATES, ACTIVITY, NOTIFICATIONS, PUBLICATIONS, STATUSES, BINS, CONFERENCES, ABSTRACT_INTENTS, GRANTS, AWARDS, PRESENTATIONS,
  personById, statusChipClass, healthLabel, priorityChip, fmtDate, relDate, daysFrom,
});
