/* MFM Research Hub — sample data */

const PEOPLE = [
  {
    "id": "u1",
    "name": "Dr. Eran Ashwal",
    "initials": "EA",
    "role": "Principal Investigator",
    "training": "MFM Staff",
    "email": "eran.ashwal@example.ca",
    "color": "#7A003C",
    "joined": "2018-09",
    "focus": "Maternal-Fetal Medicine",
    "hasPhoto": true,
    "hasCV": true,
    "bio": "Clinician-scientist in Maternal-Fetal Medicine. Research interests include placental insufficiency, hypertensive disorders of pregnancy, fetal Doppler ultrasound, and prenatal diagnosis.",
    "pubmedAuthor": "Ashwal E"
  },
  {
    "id": "u2",
    "name": "Sarah Ruddle",
    "initials": "SR",
    "role": "MFM Fellow",
    "training": "Fellow",
    "email": "",
    "color": "#0D5D78",
    "joined": "2025-11",
    "focus": "Twin pregnancy Dopplers"
  },
  {
    "id": "u3",
    "name": "Abdul Fellow",
    "initials": "AF",
    "role": "MFM Fellow",
    "training": "Fellow",
    "email": "",
    "color": "#5C002D",
    "joined": "2025-11",
    "focus": "Cerclage & preterm birth prediction"
  },
  {
    "id": "u4",
    "name": "Arbaaz Patel",
    "initials": "AP",
    "role": "Medical Student",
    "training": "Research",
    "email": "",
    "color": "#0E5B3D",
    "joined": "2025-11",
    "focus": "Fetal bowel & stomach nomograms"
  },
  {
    "id": "u5",
    "name": "Ella Chau",
    "initials": "EC",
    "role": "Medical Student",
    "training": "Research",
    "email": "",
    "color": "#137A4B",
    "joined": "2025-12",
    "focus": "Steroids timing & Doppler"
  },
  {
    "id": "u6",
    "name": "Ryley Fowler",
    "initials": "RF",
    "role": "Medical Student",
    "training": "Clerkship",
    "email": "ryley.fowler@medportal.ca",
    "color": "#B4760E",
    "joined": "2025-12",
    "focus": "Steroids timing & Doppler"
  },
  {
    "id": "u7",
    "name": "Sierra Gaudreau",
    "initials": "SG",
    "role": "Medical Student",
    "training": "Clerkship",
    "email": "sierra.gaudreau@medportal.ca",
    "color": "#9A2A2A",
    "joined": "2025-12",
    "focus": "Steroids timing & Doppler"
  },
  {
    "id": "u8",
    "name": "Manal Fodi",
    "initials": "MF",
    "role": "MFM Fellow",
    "training": "Fellow",
    "email": "",
    "color": "#7A003C",
    "joined": "2025-12",
    "focus": "GDM & neonatal outcomes"
  },
  {
    "id": "u9",
    "name": "Ali Marseu",
    "initials": "AM",
    "role": "Research Coordinator",
    "training": "Coordinator",
    "email": "",
    "color": "#B4760E",
    "joined": "2025-11",
    "focus": "Operations & protocols"
  },
  {
    "id": "u10",
    "name": "Rebecka Doohan",
    "initials": "RD",
    "role": "Research Coordinator",
    "training": "Coordinator",
    "email": "",
    "color": "#6B7785",
    "joined": "2025-11",
    "focus": "Operations"
  },
  {
    "id": "u11",
    "name": "Joseph Beyene",
    "initials": "JB",
    "role": "Biostatistician",
    "training": "Collaborator",
    "email": "",
    "color": "#0E5B3D",
    "joined": "2025-11",
    "focus": "Biostatistics"
  },
  {
    "id": "u12",
    "name": "Mackenzie Haggstrom",
    "initials": "MH",
    "role": "Collaborator",
    "training": "Collaborator",
    "email": "",
    "color": "#0D5D78",
    "joined": "2025-11",
    "focus": "Research collaborator"
  },
  {
    "id": "u13",
    "name": "Milad Alizadeh-Meghrazi",
    "initials": "MA",
    "role": "Industry Partner",
    "training": "Myant",
    "email": "miladam@myant.ca",
    "color": "#495965",
    "joined": "2025-11",
    "focus": "Wearable BP (Myant)"
  },
  {
    "id": "u14",
    "name": "Gabriela Chaves",
    "initials": "GC",
    "role": "Industry Partner",
    "training": "Myant",
    "email": "gabriela.chaves@myant.ca",
    "color": "#9C2E5E",
    "joined": "2025-11",
    "focus": "Wearable BP (Myant)"
  },
  {
    "id": "u15",
    "name": "Azar Azad",
    "initials": "AA",
    "role": "Industry Partner",
    "training": "AIvali",
    "email": "azar@aivali.org",
    "color": "#0D5D78",
    "joined": "2026-01",
    "focus": "AI ultrasound (AIvali)"
  },
  {
    "id": "u16",
    "name": "Sassan Azad",
    "initials": "SA",
    "role": "Industry Partner",
    "training": "AIvali",
    "email": "sassan@aivali.org",
    "color": "#0E5B3D",
    "joined": "2026-01",
    "focus": "AI ultrasound (AIvali)"
  }
];

const personById = (id) => PEOPLE.find(p => p.id === id);

const STATUSES = [
  'Idea / Concept', 'Protocol development', 'REB preparation', 'REB submitted', 'REB approved',
  'Data access pending', 'Data collection', 'Data cleaning', 'Statistical analysis',
  'Manuscript drafting', 'Internal review', 'Submitted to journal', 'Revision requested',
  'Accepted / Published', 'On hold', 'Completed', 'Archived'
];

const CONFERENCES = [
  { id: 'c1', name: 'SOGC Annual Clinical & Scientific Conference', short: 'SOGC 2026', dates: 'Jun 17–20, 2026', location: 'Vancouver, BC', abstractDue: '2026-02-28', earlyBird: '2026-04-15', url: 'https://sogc.org', tags: ['Canadian', 'General OB/GYN'], status: 'past_deadline' },
  { id: 'c2', name: 'SMFM Pregnancy Meeting', short: 'SMFM 2027', dates: 'Feb 1–6, 2027', location: 'Honolulu, HI', abstractDue: '2026-08-15', earlyBird: '2026-12-01', url: 'https://smfm.org', tags: ['MFM', 'High impact'], status: 'open' },
  { id: 'c3', name: 'ISUOG World Congress on Ultrasound in Obstetrics & Gynecology', short: 'ISUOG 2026', dates: 'Oct 11–15, 2026', location: 'Lisbon, Portugal', abstractDue: '2026-04-30', earlyBird: '2026-07-31', url: 'https://isuog.org', tags: ['Ultrasound', 'International'], status: 'past_deadline' },
  { id: 'c4', name: 'RCOG World Congress', short: 'RCOG 2026', dates: 'Jul 6–8, 2026', location: 'London, UK', abstractDue: '2026-03-01', earlyBird: '2026-05-01', url: 'https://rcog.org.uk', tags: ['International'], status: 'past_deadline' },
  { id: 'c5', name: 'DOHaD World Congress', short: 'DOHaD 2026', dates: 'Sep 23–26, 2026', location: 'Cape Town, South Africa', abstractDue: '2026-06-15', earlyBird: '2026-08-01', url: 'https://dohadsoc.org', tags: ['Developmental origins', 'Translational'], status: 'open' },
  { id: 'c6', name: 'Canadian Diabetes & Endocrinology Annual Meeting', short: 'CDEAM 2026', dates: 'Oct 28–31, 2026', location: 'Toronto, ON', abstractDue: '2026-06-30', earlyBird: '2026-08-15', url: '#', tags: ['Diabetes', 'Canadian'], status: 'open' },
  { id: 'c7', name: 'IFPA — Placenta Conference', short: 'IFPA 2026', dates: 'Aug 19–22, 2026', location: 'Sapporo, Japan', abstractDue: '2026-05-31', earlyBird: '2026-07-15', url: '#', tags: ['Placenta', 'International'], status: 'closing_soon' },
  { id: 'c8', name: 'CAOG Annual Conference', short: 'CAOG 2026', dates: 'Nov 12–14, 2026', location: 'Montreal, QC', abstractDue: '2026-07-31', earlyBird: '2026-09-15', url: '#', tags: ['Canadian'], status: 'open' },
];

// Project intent to submit to conferences
const ABSTRACT_INTENTS = [];


const BINS = [
  { id: 'Preterm Labour', label: 'Preterm Labour', desc: 'Spontaneous preterm birth prediction, prevention and management; cervical length screening; tocolysis; antenatal corticosteroids.', cover: 'maroon', icon: 'clock' },
  { id: 'Placenta-Mediated', label: 'Placenta-Mediated Complications', desc: 'Hypertensive disorders, fetal growth restriction, placental insufficiency biomarkers and maternal cardiovascular consequences.', cover: 'gold', icon: 'target' },
  { id: 'Diabetes', label: 'Diabetes in Pregnancy', desc: 'Gestational and pre-existing diabetes, glycemic control, fetal growth, neonatal outcomes and screening thresholds.', cover: 'bay', icon: 'activity' },
  { id: 'Ultrasound', label: 'Ultrasound & Imaging', desc: 'Obstetric ultrasound workflow, Doppler standardization, AI-assisted measurement and imaging quality protocols.', cover: 'bay', icon: 'eye' },
  { id: 'Prenatal Diagnosis', label: 'Prenatal Diagnosis', desc: 'Screening, fetal anomaly evaluation, twin pregnancy registry and diagnostic strategy.', cover: 'forest', icon: 'target' },
  { id: 'Labour & Delivery', label: 'Labour & Delivery', desc: 'Intrapartum care, postpartum hemorrhage risk, neonatal hypoglycemia and outcome stratification at term.', cover: 'grey', icon: 'stethoscope' },
];


const today = new Date('2026-05-24');
const daysFrom = (n) => {
  const d = new Date(today); d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
};

const PROJECTS = [
  {
    "id": "p1",
    "title": "Packed Cell Transfusion",
    "acronym": "PCT",
    "description": "Risk factors for packed cell transfusion in obstetric patients.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Manuscript drafting",
    "health": "green",
    "priority": "Medium",
    "progress": 80,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-11-17",
    "target": "2027-05-16",
    "lastUpdate": "2025-11-19",
    "nextMilestone": "Receiving co-author feedback on submitted manuscript.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "grey",
    "bin": "Labour & Delivery"
  },
  {
    "id": "p2",
    "title": "Non-OHIP Patients Protocol",
    "acronym": "NON-OHIP",
    "description": "MFM clinical protocol for managing non-OHIP-covered pregnant patients.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u2",
    "members": [
      "u1",
      "u2",
      "u9",
      "u10"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-11-19",
    "target": "2027-05-18",
    "lastUpdate": "2025-11-19",
    "nextMilestone": "Draft protocol circulated to McMaster team.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "grey",
    "bin": "Labour & Delivery"
  },
  {
    "id": "p3",
    "title": "Cerclage and Preterm Birth Predictors",
    "acronym": "CERC-PTB",
    "description": "Retrospective study of cerclage cases (2017–2025) to identify predictors of preterm birth following cerclage.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Data collection",
    "health": "amber",
    "priority": "Medium",
    "progress": 45,
    "pi": "u1",
    "lead": "u3",
    "members": [
      "u1",
      "u3"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-11-24",
    "target": "2027-05-23",
    "lastUpdate": "2025-11-24",
    "nextMilestone": "Abdul collecting cases using data extraction form.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "maroon",
    "bin": "Preterm Labour"
  },
  {
    "id": "p4",
    "title": "Defining Doppler in Monochorionic Pregnancies",
    "acronym": "MC-DOP",
    "description": "Defining Doppler reference values and clinical significance in MC twin pregnancies.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Idea / Concept",
    "health": "grey",
    "priority": "Medium",
    "progress": 5,
    "pi": "u1",
    "lead": "u2",
    "members": [
      "u1",
      "u2"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-11-24",
    "target": "2027-05-23",
    "lastUpdate": "2025-11-24",
    "nextMilestone": "Initial scoping with Sarah.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Ultrasound"
  },
  {
    "id": "p5",
    "title": "Bilateral Umbilical Artery Sampling",
    "acronym": "BIL-UA",
    "description": "Methods study of bilateral UA Doppler sampling reproducibility.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Idea / Concept",
    "health": "grey",
    "priority": "Medium",
    "progress": 5,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-11-26",
    "target": "2027-05-25",
    "lastUpdate": "2025-11-26",
    "nextMilestone": "Concept stage.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Ultrasound"
  },
  {
    "id": "p6",
    "title": "Fetal Stomach & Bowel Nomograms",
    "acronym": "STOM-NOM",
    "description": "Constructing fetal stomach and bowel measurement nomograms.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Data collection",
    "health": "amber",
    "priority": "Medium",
    "progress": 45,
    "pi": "u1",
    "lead": "u4",
    "members": [
      "u1",
      "u4"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-11-26",
    "target": "2027-05-25",
    "lastUpdate": "2025-11-26",
    "nextMilestone": "Arbaaz collecting reference measurements.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "forest",
    "bin": "Prenatal Diagnosis"
  },
  {
    "id": "p7",
    "title": "Steroids Timing and Doppler Changes",
    "acronym": "ST-DOP",
    "description": "Effect of antenatal corticosteroid timing on fetal Doppler indices.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Data collection",
    "health": "amber",
    "priority": "Medium",
    "progress": 45,
    "pi": "u1",
    "lead": "u5",
    "members": [
      "u1",
      "u5",
      "u6",
      "u7"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-12-01",
    "target": "2027-05-30",
    "lastUpdate": "2025-12-13",
    "nextMilestone": "Active recruitment underway.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "maroon",
    "bin": "Preterm Labour"
  },
  {
    "id": "p8",
    "title": "Neonatal Morbidity Across the Fetal Growth Spectrum in GDM",
    "acronym": "NEO-GDM",
    "description": "Neonatal morbidity across fetal growth phenotypes in gestational diabetes.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Submitted to journal",
    "health": "green",
    "priority": "Medium",
    "progress": 95,
    "pi": "u1",
    "lead": "u8",
    "members": [
      "u1",
      "u8"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-12-04",
    "target": "2027-06-03",
    "lastUpdate": "2026-01-24",
    "nextMilestone": "Submitted to AJOG as research letter.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Diabetes"
  },
  {
    "id": "p9",
    "title": "Preterm Labour Prediction Following Cerclage",
    "acronym": "CERC-PTL",
    "description": "Predicting preterm labour after cervical cerclage placement.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Data collection",
    "health": "amber",
    "priority": "Medium",
    "progress": 45,
    "pi": "u1",
    "lead": "u3",
    "members": [
      "u1",
      "u3"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-12-09",
    "target": "2027-06-08",
    "lastUpdate": "2025-12-09",
    "nextMilestone": "Initial case collection in progress.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "maroon",
    "bin": "Preterm Labour"
  },
  {
    "id": "p10",
    "title": "Wearable Blood Pressure Monitoring in Pregnancy",
    "acronym": "BP-WEAR",
    "description": "Validation of Myant wearable for continuous BP monitoring in high-risk pregnancy.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u13",
    "members": [
      "u1",
      "u13",
      "u14"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-12-11",
    "target": "2027-06-10",
    "lastUpdate": "2025-12-11",
    "nextMilestone": "Initial meeting with Myant team.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "gold",
    "bin": "Placenta-Mediated"
  },
  {
    "id": "p11",
    "title": "CSP Nomograms",
    "acronym": "CSP-NOM",
    "description": "Cavum septi pellucidi reference nomograms by gestational age.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Idea / Concept",
    "health": "grey",
    "priority": "Medium",
    "progress": 5,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-12-11",
    "target": "2027-06-10",
    "lastUpdate": "2025-12-11",
    "nextMilestone": "Concept stage.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "forest",
    "bin": "Prenatal Diagnosis"
  },
  {
    "id": "p12",
    "title": "Ultrasound Requisition Workflow Update",
    "acronym": "US-WFLW",
    "description": "Updating Epic-based ultrasound requisition workflow to improve clinical efficiency.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-12-13",
    "target": "2027-06-12",
    "lastUpdate": "2026-01-25",
    "nextMilestone": "Working with Epic team on workflow change.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Ultrasound"
  },
  {
    "id": "p13",
    "title": "CSP Measurement Protocol",
    "acronym": "CSP-PROT",
    "description": "Departmental protocol for cavum septi pellucidi measurement and management pathway.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Internal review",
    "health": "green",
    "priority": "Medium",
    "progress": 88,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2025-12-13",
    "target": "2027-06-12",
    "lastUpdate": "2025-12-13",
    "nextMilestone": "Awaiting divisional approval.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": true,
    "coverColor": "forest",
    "bin": "Prenatal Diagnosis"
  },
  {
    "id": "p14",
    "title": "Preeclampsia Orders Set",
    "acronym": "PE-ORDERS",
    "description": "Standardized preeclampsia investigations order set.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-01-25",
    "target": "2027-07-24",
    "lastUpdate": "2026-01-25",
    "nextMilestone": "Order set under development.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "gold",
    "bin": "Placenta-Mediated"
  },
  {
    "id": "p15",
    "title": "Prediction Model for Vaginal Delivery in LGA Fetuses",
    "acronym": "LGA-VD",
    "description": "Clinical prediction model for successful vaginal delivery when fetus is LGA.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-01-25",
    "target": "2027-07-24",
    "lastUpdate": "2026-01-25",
    "nextMilestone": "Model development planned.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "grey",
    "bin": "Labour & Delivery"
  },
  {
    "id": "p16",
    "title": "FGR — Perinatal Predictors & Long-Term Neurodevelopmental Outcomes",
    "acronym": "FGR-NEURO",
    "description": "Unraveling the impact of fetal growth restriction on perinatal and long-term neurodevelopmental outcomes.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-01-26",
    "target": "2027-07-25",
    "lastUpdate": "2026-01-26",
    "nextMilestone": "Protocol drafting underway.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "gold",
    "bin": "Placenta-Mediated"
  },
  {
    "id": "p17",
    "title": "AIDREA Platform Clinical Validation",
    "acronym": "AIDREA",
    "description": "Clinical validation of AIDREA AI platform for real-time obstetric ultrasound image annotation and reporting.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u15",
    "members": [
      "u1",
      "u15",
      "u16"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-01-26",
    "target": "2027-07-25",
    "lastUpdate": "2026-01-26",
    "nextMilestone": "Industry partnership with AIvali; early feasibility study.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Ultrasound"
  },
  {
    "id": "p18",
    "title": "Late-Onset FGR Phenotyping",
    "acronym": "LO-FGR",
    "description": "Phenotyping late-onset fetal growth restriction using Delphi-aligned Doppler criteria and birthweight severity.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-01-26",
    "target": "2027-07-25",
    "lastUpdate": "2026-01-27",
    "nextMilestone": "Phenotyping methodology in development.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "gold",
    "bin": "Placenta-Mediated"
  },
  {
    "id": "p19",
    "title": "Very Early Onset SGA/FGR",
    "acronym": "VEO-FGR",
    "description": "Characterizing very early onset SGA/FGR outcomes.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Idea / Concept",
    "health": "grey",
    "priority": "Medium",
    "progress": 5,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-01-27",
    "target": "2027-07-26",
    "lastUpdate": "2026-01-27",
    "nextMilestone": "Concept stage.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "gold",
    "bin": "Placenta-Mediated"
  },
  {
    "id": "p20",
    "title": "OASIS Study",
    "acronym": "OASIS",
    "description": "Obstetric outcomes study (OASIS).",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Idea / Concept",
    "health": "grey",
    "priority": "Medium",
    "progress": 5,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-01-28",
    "target": "2027-07-27",
    "lastUpdate": "2026-01-28",
    "nextMilestone": "Concept stage.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "grey",
    "bin": "Labour & Delivery"
  },
  {
    "id": "p21",
    "title": "Concordant UA Doppler Abnormalities Predicting Preterm Preeclampsia",
    "acronym": "UA-PET",
    "description": "Synergistic value of elevated pulsatility index and bilateral notching in predicting preterm preeclampsia.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Data cleaning",
    "health": "amber",
    "priority": "Medium",
    "progress": 60,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-01",
    "target": "2027-07-31",
    "lastUpdate": "2026-02-01",
    "nextMilestone": "Data being prepared for analysis.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "gold",
    "bin": "Placenta-Mediated"
  },
  {
    "id": "p22",
    "title": "Neonatal Respiratory Morbidity Prediction Model",
    "acronym": "NEO-RESP",
    "description": "Development and internal validation of prediction model for neonatal respiratory morbidity in late preterm and early term deliveries.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-01",
    "target": "2027-07-31",
    "lastUpdate": "2026-02-01",
    "nextMilestone": "Model variables being defined.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "grey",
    "bin": "Labour & Delivery"
  },
  {
    "id": "p23",
    "title": "SPV — Myant",
    "acronym": "SPV-M",
    "description": "Single-point validation with Myant wearable.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Idea / Concept",
    "health": "grey",
    "priority": "Medium",
    "progress": 5,
    "pi": "u1",
    "lead": "u13",
    "members": [
      "u1",
      "u13",
      "u14"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-01",
    "target": "2027-07-31",
    "lastUpdate": "2026-02-01",
    "nextMilestone": "Concept stage with industry partner.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Ultrasound"
  },
  {
    "id": "p24",
    "title": "GLP-1 Receptor Agonists in Pregnancy — Systematic Review",
    "acronym": "GLP1-PREG",
    "description": "Systematic review and meta-analysis of GLP-1 receptor agonists in pregnancy.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-02",
    "target": "2027-08-01",
    "lastUpdate": "2026-02-02",
    "nextMilestone": "Search strategy being finalized.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Diabetes"
  },
  {
    "id": "p25",
    "title": "Fetal Body Wall and Glycemic Control",
    "acronym": "BW-GLY",
    "description": "Relationship between maternal glycemic control and fetal body wall measurements.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Data collection",
    "health": "amber",
    "priority": "Medium",
    "progress": 45,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-06",
    "target": "2027-08-05",
    "lastUpdate": "2026-02-06",
    "nextMilestone": "Glycemic data collated.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Diabetes"
  },
  {
    "id": "p26",
    "title": "Blood Product Transfusion — Risk Factors",
    "acronym": "TRANS-RX",
    "description": "Risk factors for blood product transfusion in delivery.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Data collection",
    "health": "amber",
    "priority": "Medium",
    "progress": 45,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-06",
    "target": "2027-08-05",
    "lastUpdate": "2026-02-06",
    "nextMilestone": "Data collection form circulated.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "grey",
    "bin": "Labour & Delivery"
  },
  {
    "id": "p27",
    "title": "Vaginal Delivery in Class III Obesity Undergoing IOL — Prediction Model",
    "acronym": "OB-IOL",
    "description": "Clinical prediction model for vaginal delivery in pregnant individuals with class III obesity undergoing induction of labor.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-07",
    "target": "2027-08-06",
    "lastUpdate": "2026-02-07",
    "nextMilestone": "Variable selection in progress.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "grey",
    "bin": "Labour & Delivery"
  },
  {
    "id": "p28",
    "title": "Skeletal Dysplasia Lethality Prediction — Systematic Review",
    "acronym": "SKEL-DYS",
    "description": "Systematic review and meta-analysis of skeletal dysplasia lethality prediction models.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-08",
    "target": "2027-08-07",
    "lastUpdate": "2026-02-08",
    "nextMilestone": "SR protocol being drafted.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "forest",
    "bin": "Prenatal Diagnosis"
  },
  {
    "id": "p29",
    "title": "Early Cervical Length for sPTB — Manuscript",
    "acronym": "CL-EARLY",
    "description": "Early-gestation cervical length prediction of spontaneous preterm birth.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Internal review",
    "health": "green",
    "priority": "Medium",
    "progress": 88,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-12",
    "target": "2027-08-11",
    "lastUpdate": "2026-02-12",
    "nextMilestone": "Manuscript circulated for co-author review.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": true,
    "coverColor": "maroon",
    "bin": "Preterm Labour"
  },
  {
    "id": "p30",
    "title": "Segmental CL After Cerclage Prediction Model — Manuscript",
    "acronym": "SEG-CL",
    "description": "Segmental cervical length post-cerclage as a prediction model for sPTB.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Internal review",
    "health": "green",
    "priority": "Medium",
    "progress": 88,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-14",
    "target": "2027-08-13",
    "lastUpdate": "2026-02-14",
    "nextMilestone": "Manuscript sent for team review.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": true,
    "coverColor": "maroon",
    "bin": "Preterm Labour"
  },
  {
    "id": "p31",
    "title": "Steroids Administration & Interval to Delivery — Prediction Model",
    "acronym": "ST-INT",
    "description": "Prediction model for interval from antenatal corticosteroids to delivery.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-17",
    "target": "2027-08-16",
    "lastUpdate": "2026-02-17",
    "nextMilestone": "Model development underway.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "maroon",
    "bin": "Preterm Labour"
  },
  {
    "id": "p32",
    "title": "Cervical Length Trajectory Phenotypes After Cerclage",
    "acronym": "CL-TRAJ",
    "description": "Serial cervical length surveillance identifying distinct risk profiles for sPTB after cerclage.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Statistical analysis",
    "health": "amber",
    "priority": "Medium",
    "progress": 70,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-19",
    "target": "2027-08-18",
    "lastUpdate": "2026-02-19",
    "nextMilestone": "Trajectory phenotyping analysis underway.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "maroon",
    "bin": "Preterm Labour"
  },
  {
    "id": "p33",
    "title": "Proportional Cervical Length Change After McDonald Cerclage",
    "acronym": "PROP-CL",
    "description": "Proportional cervical length change after McDonald cerclage as a clinically practical predictor of sPTB.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Manuscript drafting",
    "health": "green",
    "priority": "Medium",
    "progress": 80,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-02-22",
    "target": "2027-08-21",
    "lastUpdate": "2026-02-22",
    "nextMilestone": "Manuscript circulated to team.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "maroon",
    "bin": "Preterm Labour"
  },
  {
    "id": "p34",
    "title": "Fetal Growth Velocity & SGA/FGR Prediction — Manuscript",
    "acronym": "FGV-SGA",
    "description": "Manuscript on fetal growth velocity and SGA/FGR prediction.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Internal review",
    "health": "green",
    "priority": "Medium",
    "progress": 88,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-03-06",
    "target": "2027-09-05",
    "lastUpdate": "2026-03-06",
    "nextMilestone": "Awaiting team feedback.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": true,
    "coverColor": "gold",
    "bin": "Placenta-Mediated"
  },
  {
    "id": "p35",
    "title": "Preterm Birth Prediction",
    "acronym": "PTB-PRED",
    "description": "Multivariable prediction of preterm birth in a contemporary cohort.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-03-13",
    "target": "2027-09-13",
    "lastUpdate": "2026-03-13",
    "nextMilestone": "Variable selection in progress.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "maroon",
    "bin": "Preterm Labour"
  },
  {
    "id": "p36",
    "title": "Prediction of Vaginal Delivery in Late-FGR",
    "acronym": "LFGR-VD",
    "description": "Predicting vaginal delivery in late-onset FGR pregnancies.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Protocol development",
    "health": "green",
    "priority": "Medium",
    "progress": 15,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Not yet submitted",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-03-13",
    "target": "2027-09-13",
    "lastUpdate": "2026-03-13",
    "nextMilestone": "Initial concept.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "grey",
    "bin": "Labour & Delivery"
  },
  {
    "id": "p37",
    "title": "Normative Fetal Growth Velocity Centiles — Canadian Cohort",
    "acronym": "NORM-FGV",
    "description": "Normative fetal growth velocity centiles and trajectory phenotyping in a contemporary Canadian cohort.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Statistical analysis",
    "health": "amber",
    "priority": "Medium",
    "progress": 70,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-03-15",
    "target": "2027-09-15",
    "lastUpdate": "2026-03-15",
    "nextMilestone": "Centile estimation in progress.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "gold",
    "bin": "Placenta-Mediated"
  },
  {
    "id": "p38",
    "title": "Impact of Fetal Doppler Reference Chart Selection",
    "acronym": "DOP-REF",
    "description": "Impact of choice of fetal Doppler reference chart on risk stratification and perinatal outcomes in singleton pregnancies.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Statistical analysis",
    "health": "green",
    "priority": "Medium",
    "progress": 70,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-03-29",
    "target": "2027-09-29",
    "lastUpdate": "2026-03-29",
    "nextMilestone": "Comparative analysis underway.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Ultrasound"
  },
  {
    "id": "p39",
    "title": "Fetal Doppler Indices as Continuous Predictors",
    "acronym": "DOP-CONT",
    "description": "Fetal Doppler indices as continuous predictors of adverse perinatal outcome, compared with conventional binary thresholds.",
    "category": "Clinical research",
    "studyDesign": "TBD",
    "status": "Statistical analysis",
    "health": "green",
    "priority": "Medium",
    "progress": 70,
    "pi": "u1",
    "lead": "u1",
    "members": [
      "u1"
    ],
    "reb": "Approved",
    "dataSource": "TBD",
    "targetJournal": "TBD",
    "start": "2026-04-03",
    "target": "2027-10-03",
    "lastUpdate": "2026-04-03",
    "nextMilestone": "Continuous-predictor modeling.",
    "nextDue": "2026-06-23",
    "fileCount": 0,
    "awaitingUpdate": false,
    "awaitingReview": false,
    "coverColor": "bay",
    "bin": "Ultrasound"
  }
];

const MILESTONES = {};

const TASKS = {};

const UPDATES = [];

const ACTIVITY = [];

const NOTIFICATIONS = [];

const PUBLICATIONS = [
  { id: 'pub1', pmid: '40123456', year: 2026, month: 'Mar', title: 'Mid-trimester cervical length and risk of spontaneous preterm birth in low-risk pregnancies: a multi-centre cohort analysis', authors: 'Ashwal E, Shah P, Sokolov E, Park A, et al.', journal: 'BJOG', volume: '133(4)', pages: '442–453', doi: '10.1111/1471-0528.17852', type: 'Original article', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub2', pmid: '39654321', year: 2025, month: 'Nov', title: 'Maternal cardiac remodelling in preeclampsia: a systematic echocardiographic review', authors: 'Marchetti S, Ashwal E, Park A.', journal: 'Hypertension in Pregnancy', volume: '44(3)', pages: '155–168', doi: '10.1080/10641955.2025.2298142', type: 'Review', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub3', pmid: '39512876', year: 2025, month: 'Aug', title: 'Doppler indices following antenatal corticosteroids in late preterm pregnancy: a prospective observational pilot', authors: 'Ashwal E, Okafor J, Marchetti S.', journal: 'Ultrasound Obstet Gynecol', volume: '66(2)', pages: '189–197', doi: '10.1002/uog.27812', type: 'Original article', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub4', pmid: '39301142', year: 2025, month: 'May', title: 'Antenatal corticosteroids in late preterm pregnancy: a network meta-analysis of timing strategies', authors: 'Okafor J, Pritchard O, Ashwal E.', journal: 'Cochrane Database Syst Rev', volume: '2025(5)', pages: 'CD014731', doi: '10.1002/14651858.CD014731', type: 'Systematic review', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub5', pmid: '38997254', year: 2024, month: 'Dec', title: 'Twin pregnancy registry: design, governance and baseline characteristics', authors: 'Shah P, Voss R, Ashwal E.', journal: 'J Obstet Gynaecol Can', volume: '46(12)', pages: '102589', doi: '10.1016/j.jogc.2024.102589', type: 'Methods', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub6', pmid: '38812011', year: 2024, month: 'Jul', title: 'Maternal BMI and short-term Doppler variability after betamethasone: a sub-analysis', authors: 'Ashwal E, Marchetti S.', journal: 'Acta Obstet Gynecol Scand', volume: '103(7)', pages: '1322–1330', doi: '10.1111/aogs.14821', type: 'Original article', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub7', pmid: '38456712', year: 2024, month: 'Mar', title: 'Hypertensive disorders of pregnancy and long-term maternal cardiovascular outcomes: a Canadian cohort', authors: 'Park A, Tran D, Ashwal E.', journal: 'Pregnancy Hypertens', volume: '35', pages: '88–95', doi: '10.1016/j.preghy.2024.02.008', type: 'Original article', status: 'Published', source: 'pubmed', addedBy: 'auto' },
  { id: 'pub8', pmid: 'in-press', year: 2026, month: 'In press', title: 'Neonatal hypoglycemia in late-preterm infants: a case-control analysis of perinatal predictors', authors: 'Chen W, Pritchard O, Ashwal E.', journal: 'Journal of Pediatrics', volume: 'In press', pages: '—', doi: 'pending', type: 'Original article', status: 'Accepted', source: 'manual', addedBy: 'u1' },
  { id: 'pub9', pmid: '37992145', year: 2023, month: 'Sep', title: 'Cervical length screening: implementation in a busy MFM clinic — lessons learned', authors: 'Ashwal E, Krishnan A.', journal: 'J Matern Fetal Neonatal Med', volume: '36(9)', pages: '2241712', doi: '10.1080/14767058.2023.2241712', type: 'Commentary', status: 'Published', source: 'pubmed', addedBy: 'auto' },
];

const GRANTS = [];

const AWARDS = [];

const PRESENTATIONS = [];

// chip colour helpers
const statusChipClass = (status) => {
  const s = status.toLowerCase();
  if (s.includes('idea') || s.includes('protocol dev') || s.includes('hold') || s.includes('archived')) return 'chip-grey';
  if (s.includes('reb prep') || s.includes('reb submitted') || s.includes('data access')) return 'chip-amber';
  if (s.includes('reb approved') || s.includes('data collection') || s.includes('data cleaning')) return 'chip-bayfront';
  if (s.includes('statistical') || s.includes('manuscript') || s.includes('internal review')) return 'chip-maroon';
  if (s.includes('submitted to journal') || s.includes('revision')) return 'chip-gold';
  if (s.includes('accepted') || s.includes('completed')) return 'chip-green';
  return 'chip-grey';
};

const healthLabel = (h) => ({ green: 'On track', amber: 'Needs attention', red: 'Delayed', grey: 'Inactive' }[h] || h);
const priorityChip = (p) => ({ High: 'chip-red', Medium: 'chip-amber', Low: 'chip-grey' }[p] || 'chip-grey');

const fmtDate = (iso) => {
  if (!iso) return '—';
  const d = new Date(iso);
  return d.toLocaleDateString('en-CA', { month: 'short', day: 'numeric', year: 'numeric' });
};
const relDate = (iso) => {
  if (!iso) return '—';
  // Parse YYYY-MM-DD as LOCAL midnight (not UTC) — otherwise late-evening Toronto
  // values get shifted a day in the comparison below.
  let d;
  if (/^\d{4}-\d{2}-\d{2}$/.test(iso)) {
    const [y, m, day] = iso.split('-').map(Number);
    d = new Date(y, m - 1, day);
  } else {
    d = new Date(iso);
  }
  const todayLocal = new Date();
  todayLocal.setHours(0, 0, 0, 0);
  d.setHours(0, 0, 0, 0);
  const diff = Math.round((d - todayLocal) / (24 * 3600 * 1000));
  if (diff === 0) return 'Today';
  if (diff === 1) return 'Tomorrow';
  if (diff === -1) return 'Yesterday';
  if (diff > 0 && diff < 14) return `in ${diff}d`;
  if (diff < 0 && diff > -14) return `${-diff}d ago`;
  return fmtDate(iso);
};

Object.assign(window, {
  PEOPLE, PROJECTS, MILESTONES, TASKS, UPDATES, ACTIVITY, NOTIFICATIONS, PUBLICATIONS, STATUSES, BINS, CONFERENCES, ABSTRACT_INTENTS, GRANTS, AWARDS, PRESENTATIONS,
  personById, statusChipClass, healthLabel, priorityChip, fmtDate, relDate, daysFrom,
});
